### PR TITLE
Sherlock issue 52

### PR DESCRIPTION
**Pull request by davidbrai**

### CODE REVIEW

**Comment by davidbrai** [comment]
not reviewing this right now because it's linked to the bigger change around blacklisted tokens

**Comment by eladmallel** [comment]
@davidbrai I agree we can probably not use this PR since its changes are part of #6 
still possibly useful as a link to Sherlock to show the fix in isolation

**Comment by davidbrai** [comment]
@eladmallel would rather show fixes in their full context if someone (watchpug?) is going to review them

**Comment by eladmallel** [comment]
closing since this fix is part of #6

**Pull request closed without merging**
